// Builds the MonxuPlan browser edition into ./dist:
//
//   dist/index.html          the page (inline CSS + JS: the web app's pages, router and API bridge)
//   dist/backend-worker.js   Web Worker hosting the Python API
//   dist/py/*.json           Python standard library, MonxuPlan backend and its dependencies (JSON bundles)
//   dist/pyodide/…           the Pyodide runtime (CPython compiled to WebAssembly)
//
// Usage: npm install && node build.mjs   (needs python3 + pip for the wheels)
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const FRONT = path.join(ROOT, "frontend");
const DIST = path.join(HERE, "dist");
const CACHE = path.join(HERE, ".cache");
const PYODIDE = path.join(HERE, "node_modules", "pyodide");
const PYODIDE_FILES = ["pyodide.mjs", "pyodide.asm.mjs", "pyodide.asm.wasm", "pyodide-lock.json"];

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(path.join(DIST, "pyodide"), { recursive: true });
fs.mkdirSync(CACHE, { recursive: true });

// 1. routes: every page of the Next.js app directory
function routes() {
  const base = path.join(FRONT, "src", "app");
  const out = [];
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name === "page.tsx") out.push(path.relative(base, dir));
    }
  };
  walk(base);
  const pages = out
    .map((rel) => ({ rel, route: "/" + rel.split(path.sep).filter((s) => !s.startsWith("(")).join("/") }))
    .filter((r) => r.route !== "/" && !r.route.startsWith("/login"))
    .sort((a, b) => b.route.split("/").length - a.route.split("/").length || a.route.localeCompare(b.route));
  const imports = pages.map((p, i) => `import P${i} from "@/app/${p.rel.split(path.sep).join("/")}/page";`).join("\n");
  const table = pages.map((p, i) => `  [${JSON.stringify(p.route)}, P${i}],`).join("\n");
  fs.writeFileSync(
    path.join(HERE, "spa", "routes.ts"),
    `// Generated by build.mjs from frontend/src/app — do not edit.
import type { ComponentType } from "react";
${imports}

const ROUTES: [string, ComponentType][] = [
${table}
];

function match(pattern: string, pathname: string): Record<string, string> | null {
  const a = pattern.split("/");
  const b = pathname.split("/");
  if (a.length !== b.length) return null;
  const params: Record<string, string> = {};
  for (let i = 0; i < a.length; i++) {
    if (a[i].startsWith("[") && a[i].endsWith("]")) params[a[i].slice(1, -1)] = decodeURIComponent(b[i]);
    else if (a[i] !== b[i]) return null;
  }
  return params;
}

export function resolveRoute(pathname: string): ComponentType {
  for (const [pattern, page] of ROUTES) if (match(pattern, pathname)) return page;
  return ROUTES.find(([p]) => p === "/dashboard")![1];
}

export function matchParams(pathname: string): Record<string, string> {
  for (const [pattern] of ROUTES) {
    const m = match(pattern, pathname);
    if (m) return m;
  }
  return {};
}
`,
  );
  return pages.length;
}
console.log(`routes: ${routes()} pages`);

// 2. fonts: Latin subsets of the app's self-hosted fonts, embedded
function fontsCss() {
  const sources = [
    path.join(FRONT, "node_modules/@fontsource-variable/inter/index.css"),
    path.join(FRONT, "node_modules/@fontsource/ibm-plex-mono/400.css"),
    path.join(FRONT, "node_modules/@fontsource/ibm-plex-mono/500.css"),
  ];
  let css = "";
  for (const file of sources) {
    const text = fs.readFileSync(file, "utf8");
    for (const block of text.split(/(?=\/\*)/)) {
      const name = (block.match(/\/\*\s*([^*]+?)\s*\*\//) || [])[1] || "";
      if (!/-latin-/.test(name)) continue;
      css += block.replace(/url\(\.\/files\/([^)]+)\)/g, (_, f) => {
        const buf = fs.readFileSync(path.join(path.dirname(file), "files", f));
        return `url(data:font/woff2;base64,${buf.toString("base64")})`;
      });
    }
  }
  return css;
}

// 3. Tailwind: the app's own globals.css, compiled against the app sources
async function tailwindCss() {
  const req = (await import("node:module")).createRequire(path.join(FRONT, "package.json"));
  const postcss = req("postcss");
  const tailwind = req("@tailwindcss/postcss");
  const from = path.join(FRONT, "src", "app", "globals.css");
  const res = await postcss([tailwind({ base: path.join(FRONT, "src"), optimize: { minify: true } })]).process(fs.readFileSync(from, "utf8"), { from });
  return res.css;
}

const BOOT_CSS = `
#monxuplan-root{height:100%}
.boot{min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0b1a30;padding:24px 16px;font-family:"Inter Variable",system-ui,sans-serif;color:#e6edf7}
.boot-card{width:100%;max-width:440px;display:flex;flex-direction:column;gap:14px}
.boot-brand{display:flex;align-items:center;gap:10px;font-weight:600;font-size:15px;letter-spacing:-.01em}
.boot h1{font-size:19px;line-height:1.3;font-weight:600;margin:0;text-wrap:balance}
.boot-steps{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px;font-size:13.5px}
.boot-steps li{display:flex;align-items:center;gap:10px;color:#8ea3c2}
.boot-steps li[data-state=done]{color:#cfe0f7}
.boot-steps li[data-state=active]{color:#fff;font-weight:600}
.boot-dot{width:18px;height:18px;border-radius:50%;border:1.5px solid #3b5478;display:inline-flex;align-items:center;justify-content:center;font-size:11px}
.boot-steps li[data-state=done] .boot-dot{background:#1baf7a;border-color:#1baf7a;color:#fff}
.boot-steps li[data-state=active] .boot-dot{border-color:#6fa8ff;border-top-color:transparent;animation:boot-spin .8s linear infinite}
.boot-detail{font-size:12.5px;color:#a9bad3;margin:0;font-variant-numeric:tabular-nums}
.boot-note{font-size:12px;color:#7f93b2;margin:0;line-height:1.5}
.boot-error{font:12px/1.45 "IBM Plex Mono",ui-monospace,monospace;background:#051022;border:1px solid #243a5c;padding:10px;white-space:pre-wrap;max-height:40vh;overflow:auto;color:#ffb4a8}
@keyframes boot-spin{to{transform:rotate(360deg)}}
@media (prefers-reduced-motion:reduce){.boot-steps li[data-state=active] .boot-dot{animation:none}}
`;

// 4. JavaScript bundle
const shim = (f) => path.join(HERE, "spa", "shims", f);
const js = await esbuild.build({
  entryPoints: [path.join(HERE, "spa", "main.tsx")],
  bundle: true,
  write: false,
  minify: true,
  format: "iife",
  target: ["es2022"],
  jsx: "automatic",
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  nodePaths: [path.join(FRONT, "node_modules")],
  alias: {
    "next/link": shim("next-link.tsx"),
    "next/navigation": shim("next-navigation.ts"),
  },
  plugins: [
    {
      name: "monxuplan-browser",
      setup(b) {
        b.onResolve({ filter: /^@\/lib\/(loc|save)$/ }, (a) => ({ path: shim(a.path.split("/").pop() + ".ts") }));
        b.onResolve({ filter: /^\.\/(loc|save)$/ }, (a) => (a.importer.includes(path.join("frontend", "src", "lib")) ? { path: shim(a.path.slice(2) + ".ts") } : undefined));
        b.onResolve({ filter: /^@\// }, (a) => {
          const base = path.join(FRONT, "src", a.path.slice(2));
          for (const ext of ["", ".ts", ".tsx", "/index.ts", "/index.tsx"]) if (fs.existsSync(base + ext) && fs.statSync(base + ext).isFile()) return { path: base + ext };
          return undefined;
        });
        b.onLoad({ filter: /\.css$/ }, () => ({ contents: "", loader: "js" }));
      },
    },
  ],
});
const bundle = js.outputFiles[0].text;

const css = fontsCss() + (await tailwindCss()) + BOOT_CSS;

// 5. page (the artifact host wraps it in its own document skeleton)
const page = `<title>MonxuPlan</title>
<style>${css}</style>
<div id="monxuplan-root"></div>
<script>${bundle.replace(/<\/script/gi, "<\\/script")}</script>
`;
fs.writeFileSync(path.join(DIST, "index.html"), page);
fs.copyFileSync(path.join(HERE, "worker", "backend-worker.js"), path.join(DIST, "backend-worker.js"));

// 6. Pyodide runtime
for (const f of PYODIDE_FILES) fs.copyFileSync(path.join(PYODIDE, f), path.join(DIST, "pyodide", f));

// 7. Python packages
const wheels = path.join(CACHE, "wheels");
if (!fs.existsSync(wheels) || !fs.readdirSync(wheels).length) {
  fs.mkdirSync(wheels, { recursive: true });
  execFileSync(
    "pip",
    ["download", "--pre", "--only-binary=:all:", "--platform", "pyemscripten_2026_0_wasm32", "--platform", "any", "--python-version", "3.14", "--implementation", "cp", "--abi", "cp314", "--abi", "abi3", "--abi", "none", "-d", wheels, "-r", path.join(HERE, "requirements-browser.txt")],
    { stdio: "inherit" },
  );
}
execFileSync("python3", [path.join(HERE, "build_site.py"), wheels, path.join(PYODIDE, "python_stdlib.zip"), path.join(DIST, "py")], { stdio: "inherit" });

const size = (f) => (fs.statSync(path.join(DIST, f)).size / 1e6).toFixed(2) + " MB";
console.log(`index.html ${size("index.html")}, pyodide.asm.wasm ${size("pyodide/pyodide.asm.wasm")}`);
