// Generated by build.mjs from frontend/src/app — do not edit.
import type { ComponentType } from "react";
import P0 from "@/app/(app)/admin/data-quality/page";
import P1 from "@/app/(app)/analytics/plan-vs-actual/page";
import P2 from "@/app/(app)/master-data/[entity]/page";
import P3 from "@/app/(app)/planning/alerts/page";
import P4 from "@/app/(app)/planning/capacity/page";
import P5 from "@/app/(app)/planning/gantt/page";
import P6 from "@/app/(app)/planning/materials/page";
import P7 from "@/app/(app)/planning/mps/page";
import P8 from "@/app/(app)/planning/orders/page";
import P9 from "@/app/(app)/planning/scenarios/page";
import P10 from "@/app/(app)/shopfloor/dispatch/page";
import P11 from "@/app/(app)/shopfloor/operator/page";
import P12 from "@/app/(app)/shopfloor/supervisor/page";
import P13 from "@/app/(app)/admin/page";
import P14 from "@/app/(app)/analytics/page";
import P15 from "@/app/(app)/dashboard/page";
import P16 from "@/app/(app)/getting-started/page";
import P17 from "@/app/(app)/integrations/page";
import P18 from "@/app/(app)/master-data/page";
import P19 from "@/app/(app)/planning/page";

const ROUTES: [string, ComponentType][] = [
  ["/admin/data-quality", P0],
  ["/analytics/plan-vs-actual", P1],
  ["/master-data/[entity]", P2],
  ["/planning/alerts", P3],
  ["/planning/capacity", P4],
  ["/planning/gantt", P5],
  ["/planning/materials", P6],
  ["/planning/mps", P7],
  ["/planning/orders", P8],
  ["/planning/scenarios", P9],
  ["/shopfloor/dispatch", P10],
  ["/shopfloor/operator", P11],
  ["/shopfloor/supervisor", P12],
  ["/admin", P13],
  ["/analytics", P14],
  ["/dashboard", P15],
  ["/getting-started", P16],
  ["/integrations", P17],
  ["/master-data", P18],
  ["/planning", P19],
];

function match(pattern: string, pathname: string): Record<string, string> | null {
  const a = pattern.split("/");
  const b = pathname.split("/");
  if (a.length !== b.length) return null;
  const params: Record<string, string> = {};
  for (let i = 0; i < a.length; i++) {
    if (a[i].startsWith("[") && a[i].endsWith("]")) params[a[i].slice(1, -1)] = decodeURIComponent(b[i]);
    else if (a[i] !== b[i]) return null;
  }
  return params;
}

export function resolveRoute(pathname: string): ComponentType {
  for (const [pattern, page] of ROUTES) if (match(pattern, pathname)) return page;
  return ROUTES.find(([p]) => p === "/dashboard")![1];
}

export function matchParams(pathname: string): Record<string, string> {
  for (const [pattern] of ROUTES) {
    const m = match(pattern, pathname);
    if (m) return m;
  }
  return {};
}
