// Terms the API sends as data and the interface translates with t(value) (objective presets, time
// profiles…). Listed here so `npm run i18n:check` knows they are used.
export const SERVER_TERMS = ["OTIF First", "Minimize Setup", "Max Throughput", "Minimize Inventory", "Stable Plan", "Balanced", "Quick", "Normal", "Deep",
  // planning run steps
  "Load scenario", "Validate master data", "Validate constraints", "Explode BOM", "Calculate material availability", "Generate operations", "Generate feasible resource alternatives", "Build calendars", "Build setup matrices", "Identify bottlenecks", "Generate initial feasible schedule", "Optimize", "Repair violations", "Calculate KPIs", "Generate explanations", "Save schedule", "Publish result", "Generating initial plan", "Optimizing",
  // delay cause categories
  "Material", "Data", "Capacity", "Lead time", "Machine", "Labor", "Tool", "Calendar", "Priority",
  // KPI catalogue (groups and labels) and drill-down levels
  "Customer service", "Production", "Resources", "Materials", "Plan quality", "Cost", "Sustainability",
  "OTIF", "On-time delivery", "Late orders", "Average delay", "Maximum delay", "Past-due orders", "Unscheduled orders", "Throughput (horizon)", "Lead time", "Cycle time", "WIP (avg orders)", "Setup time", "Queue time", "Utilisation", "Idle time", "Overtime", "Material shortages", "Operations delayed by material", "Materials below safety stock", "Hard violations", "Soft deviations", "Frozen zone changes", "Operations moved vs baseline", "Average shift vs baseline", "Planned cost", "Energy", "CO₂ estimate", "Orders", "Late or unscheduled", "Unknown",
  "No published plan covers the executed operations of this period yet.",
  "Copy the key now; only a hash is stored.",
  "Store the signing secret now; it will not be shown again.",
  // data-quality checks (titles, hints, problems, example columns)
  "Products without BOM", "Make items need a bill of materials for material planning.", "Products with open orders but no routing", "Orders of these products cannot be scheduled.", "Open orders without operations", "Generate operations from the routing or import them.", "Operations without a feasible resource", "Add a primary or alternative resource in the routing.", "Operations assigned to an empty resource group", "The group has no active resource in this plant.", "Resources without calendar", "They would be treated as available 24/7.", "Materials without unit of measure", "Quantities cannot be interpreted without a unit.", "Open orders already past their due date", "Review promised dates with the customer.", "Orders with zero or negative quantity", "Correct the quantity.", "Invalid routings", "Fix sequence numbers, precedences and times.", "Circular BOMs", "A component cannot contain its own parent.", "Items without the attribute used by a setup matrix", "The matrix default changeover time will be used.", "Skill / labour pool inconsistencies", "Operations requiring these pools may be infeasible.", "Overdue purchase receipts", "Confirm new dates with the supplier: planning assumes they arrive now.", "duplicate sequence numbers", "precedence references a missing operation", "precedence cycle", "operation has no run time", "pool without skill", "member lacks the pool skill", "pool without operators", "code", "open orders", "name", "number", "due", "routing", "operation", "problem", "attribute", "matrix", "labor pool", "operator", "purchase order", "line", "item", "expected",
  // data tables, import templates and their groups
  "BOM", "lines", "Calendar", "exceptions", "shifts", "Company", "Customer", "Demand", "Downtime", "Inventory", "Inventory transaction", "Item", "Item per plant (sourcing)", "Labour pool", "Machine", "Maintenance", "Material", "Material lot", "Operator", "Operator absence", "skills", "Optimisation profile", "Order operation", "Planning area", "Planning rule", "Plant", "Product", "Product family", "Production order", "operations", "Production report (actuals)", "Purchase order", "Resource", "Resource group", "members", "Routing", "Routing operation", "resources", "precedences", "Sales order", "Sequence rule", "Setup matrix", "entries", "Setup rule", "Site", "Skill", "Supplier", "Tool", "Tool compatibility", "Transfer lane", "Unit conversion", "Unit of measure", "Work center", "Bills of materials", "Calendars (shift patterns)", "Customers", "Demand (forecast and independent demand)", "Inventory (on hand)", "Items (products and materials)", "Maintenance and downtime", "Production orders", "Purchase orders (open receipts)", "Resources (machines, lines, tools, labour pools)", "Routings (operations and resources)", "Suppliers", "Business partners", "Calendars", "Execution", "Labour", "Orders", "Organisation", "Planning configuration", "Products", "Resources", "Supply chain",
  // alert and attention texts (templates with their values in context.i18n)
  "{n} orders at risk", "{n} orders finish after their due date ({hp} high priority).", "{order} late by {h} h", "Due {due_at}, planned end {end_at} ({tz})", "{n} due dates impossible", "Even at infinite capacity these orders cannot meet their date (lead time or material).", "{n} operations blocked by material shortage", "{n} operations without feasible slot", "{n} operations without compatible resource", "{n} operations waiting for unscheduled predecessors", "{n} operations unscheduled ({reason})", "{res} overloaded {h} h", "Requirement {req} h vs capacity {cap} h; {n} late orders waited on it.", "Material {m} delays {n} orders", "Late or insufficient supply.", "{res}: {h} h of waiting", "Operations waited for labour availability.", "Operations waited for tool availability.", "{n} materials would go negative", "Material shortage allowed by the scenario settings.", "{res} down", "Unplanned downtime", "{n} orders past due", "Their due date is already in the past.", "{m}: receipt {po} delayed", "Last planning run failed", "{res} is down", "{res} is in maintenance", "{res} is {status}", "Reported by the shop floor. Check the plan impact and reschedule if needed.", "{plan} is not published", "The shop floor still works with {plan}.", "No plan yet", "Run the planner to create the first plan of this plant.",
  // password rules (error context of WEAK_PASSWORD)
  "at least 10 characters", "upper and lower case letters", "a digit",
  // delay causes (engine templates, fixed terms)
  "Even at infinite capacity the order cannot finish before {end_at} (limited by {limit_term})", "the planning start", "the release date", "material availability", "operations already fixed or in progress", "the lead time", "no feasible resource", "the predecessors", "{op} on {res} waited {h} h for material {material}", "{op} on {res} waited {h} h for {wait_term}", "the machine", "a changeover", "qualified operators", "a tool", "working time", "Sequencing decision: other orders were given priority",
  // connector systems
  "Database (PostgreSQL, MySQL/MariaDB, SQL Server, Oracle, SQLite): read tables or SELECT queries", "File drop (CSV/Excel/JSON via the import wizard or API)", "Generic REST (push events to /api/v1/events, pull data with API keys)", "MES (generic)",
  // unscheduled operations (causes and alert summaries)
  "{op} cannot start: material shortage of {materials}", "Short materials: {materials}. Operations: {ops}", "Waiting operations: {ops}", "Operations: {ops}", "{op} waits for {predecessor}, which could not be scheduled", "{op} has no compatible resource (check routing / planning rules)", "{op} is part of a precedence cycle",
  // supervisor delay reasons
  "planned start passed, not started", "should be finished",
] as const;
