// Where an alert leads: every alert carries the context of the entity it is about.

export type AlertRow = { id: string; type?: string; source?: string; context?: Record<string, any> | null };

export function alertHref(a: AlertRow): string {
  const c = a.context || {};
  switch (c.page) {
    case "order":
      return c.order_number ? `/planning/orders?q=${encodeURIComponent(c.order_number)}` : "/planning/orders";
    case "orders":
      return c.filter?.status ? `/planning/orders?status=${encodeURIComponent(c.filter.status)}` : "/planning/orders";
    case "capacity":
      return c.resource_code ? `/planning/capacity?resource=${encodeURIComponent(c.resource_code)}` : "/planning/capacity";
    case "materials":
      return c.material ? `/planning/materials?material=${encodeURIComponent(c.material)}` : "/planning/materials";
    case "resources":
      return "/shopfloor/supervisor";
    case "planning":
      return "/planning";
  }
  if (c.order_number) return `/planning/orders?q=${encodeURIComponent(c.order_number)}`;
  if (a.type?.startsWith("MATERIAL")) return "/planning/materials";
  if (c.resource_id) return "/planning/capacity";
  if (a.source === "PLAN") return "/planning";
  return "/planning/alerts";
}

type I18nText = { key: string; values?: Record<string, string | number | null> };
type Texted = { [field: string]: any; i18n?: Record<string, I18nText> | null; context?: Record<string, any> | null };

/** A text generated by the server (alert title or message, delay cause…) in the user's language: the
 * server sends the English template and its values next to the rendered English text. Values ending in
 * "_at" are date-times (shown in the user's format), in "_term" fixed phrases (translated). Without a
 * template (older data) the English text is shown. */
export function serverText(t: (k: string, v?: Record<string, string | number>) => string, fmt: (iso: string) => string, a: Texted | null | undefined, part: string, fallback?: string): string {
  if (!a) return "";
  const tx = (a.i18n || a.context?.i18n)?.[part] as I18nText | undefined;
  if (!tx) return (fallback !== undefined ? a[fallback] : a[part]) || "";
  const values: Record<string, string | number> = {};
  for (const [k, v] of Object.entries(tx.values || {})) values[k] = v === null || v === undefined ? "—" : k.endsWith("_at") ? fmt(String(v)) : k.endsWith("_term") ? t(String(v)) : v;
  return t(tx.key, values);
}

export const alertText = (t: Parameters<typeof serverText>[0], fmt: (iso: string) => string, a: Texted, part: "title" | "message") => serverText(t, fmt, a, part);

type Unscheduled = { op_id?: string; reason?: string; message?: string; details?: Record<string, any> | null };

/** Why an operation could not be scheduled, in the user's language, rebuilt from the reason code and
 * its details; reasons whose details carry free text keep the engine's English message. */
export function unscheduledText(t: (k: string, v?: Record<string, string | number>) => string, u: Unscheduled | null | undefined): string {
  if (!u) return "";
  const op = u.op_id || "";
  const d = u.details || {};
  switch (u.reason) {
    case "MATERIAL_SHORTAGE": {
      const mats = (d.materials || []) as { material: string; required: number; available: number }[];
      if (!mats.length) break;
      const list = mats.map((m) => t("{material} (needs {need}, available {avail})", { material: m.material, need: m.required, avail: m.available })).join(", ");
      return t("{op} cannot start: material shortage {materials}", { op, materials: list });
    }
    case "PREDECESSOR_UNSCHEDULED":
      if (d.predecessor) return t("{op} waits for {predecessor}, which could not be scheduled", { op, predecessor: d.predecessor });
      break;
    case "NO_COMPATIBLE_RESOURCE":
      return t("{op} has no compatible resource (check routing / planning rules)", { op });
    case "PRECEDENCE_CYCLE":
      return t("{op} is part of a precedence cycle", { op });
  }
  return u.message || "";
}
